In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import openpyxl
import xlrd

In [ ]:
df = pd.read_excel('../Data/fetal_health_base.xlsx')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   baseline value                                          2126 non-null   float64
 1   accelerations                                           2126 non-null   float64
 2   fetal_movement                                          2126 non-null   float64
 3   uterine_contractions                                    2126 non-null   float64
 4   light_decelerations                                     2126 non-null   float64
 5   severe_decelerations                                    2126 non-null   float64
 6   prolongued_decelerations                                2126 non-null   float64
 7   abnormal_short_term_variability                         2126 non-null   float64
 8   mean_value_of_short_term_variability                    2126 non-null   object
 9   percentage_of_time_with_abnormal_long_term_variability  2126 non-null   float64
 10  mean_value_of_long_term_variability                     2126 non-null   object
 11  histogram_width                                         2126 non-null   float64
 12  histogram_min                                           2126 non-null   float64
 13  histogram_max                                           2126 non-null   float64
 14  histogram_number_of_peaks                               2126 non-null   float64
 15  histogram_number_of_zeroes                              2126 non-null   float64
 16  histogram_mode                                          2126 non-null   float64
 17  histogram_mean                                          2126 non-null   float64
 18  histogram_median                                        2126 non-null   float64
 19  histogram_variance                                      2126 non-null   float64
 20  histogram_tendency                                      2126 non-null   float64
 21  fetal_health                                            2126 non-null   float64
dtypes: float64(20), object(2)
memory usage: 365.5+ KB

In [ ]:
#visualizar duas colunas objects apenas
df[['mean_value_of_short_term_variability', 'mean_value_of_long_term_variability']].head()

  mean_value_of_short_term_variability mean_value_of_long_term_variability
0                                  0.5                 2026-04-02 00:00:00
1                  2026-01-02 00:00:00                 2026-04-10 00:00:00
2                  2026-01-02 00:00:00                 2026-04-13 00:00:00
3                  2026-04-02 00:00:00                                23.0
4                  2026-04-02 00:00:00                 2026-09-19 00:00:00

### Tratamento das colunas object
As duas colunas, se o valor foi 0 marcou como date. A partir disso vou fazer a troca desses valores para valores float64

In [ ]:
#tirar o valor todo que tiver ...00:00:00... na sting e substituir por 0

colunas_alvo = ['mean_value_of_short_term_variability', 'mean_value_of_long_term_variability']

for coluna in colunas_alvo:
    teste = pd.to_datetime(df[coluna], errors='coerce', format='mixed')
    df[coluna] = df[coluna].mask(teste.notna(), 0)
    df[coluna] = pd.to_numeric(df[coluna], errors='coerce')

#verificar se a substituição foi feita corretamente
display(df[['mean_value_of_short_term_variability', 'mean_value_of_long_term_variability']].head(10))

df.info()

   mean_value_of_short_term_variability  mean_value_of_long_term_variability
0                                   0.0                                  0.0
1                                   0.0                                  0.0
2                                   0.0                                  0.0
3                                   0.0                                  0.0
4                                   0.0                                  0.0
5                                   0.0                                  0.0
6                                   0.0                                  0.0
7                                   0.0                                  0.0
8                                   0.0                                  0.0
9                                   0.0                                  0.0

<class 'pandas.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   baseline value                                          2126 non-null   float64
 1   accelerations                                           2126 non-null   float64
 2   fetal_movement                                          2126 non-null   float64
 3   uterine_contractions                                    2126 non-null   float64
 4   light_decelerations                                     2126 non-null   float64
 5   severe_decelerations                                    2126 non-null   float64
 6   prolongued_decelerations                                2126 non-null   float64
 7   abnormal_short_term_variability                         2126 non-null   float64
 8   mean_value_of_short_term_variability                    2126 non-null   float64
 9   percentage_of_time_with_abnormal_long_term_variability  2126 non-null   float64
 10  mean_value_of_long_term_variability                     2126 non-null   float64
 11  histogram_width                                         2126 non-null   float64
 12  histogram_min                                           2126 non-null   float64
 13  histogram_max                                           2126 non-null   float64
 14  histogram_number_of_peaks                               2126 non-null   float64
 15  histogram_number_of_zeroes                              2126 non-null   float64
 16  histogram_mode                                          2126 non-null   float64
 17  histogram_mean                                          2126 non-null   float64
 18  histogram_median                                        2126 non-null   float64
 19  histogram_variance                                      2126 non-null   float64
 20  histogram_tendency                                      2126 non-null   float64
 21  fetal_health                                            2126 non-null   float64
dtypes: float64(22)
memory usage: 365.5 KB

### Agora que não temos valores faltantes ou valores do tipo diferente, podemos ir para algumas análises das colunas